- name: network
  type: group
  description: >
    Network metrics.
  release: ga
  fields:

    - name: interface
      type: keyword
      description: >
        Network interface name.
    - name: in
      type: group
      description: >
        Incoming network stats per second.
      fields:
        - name: bytes
          type: double
          format: bytes
          description: >
            Incoming bytes per seconds.
        - name: dropped
          type: double
          description: >
            Dropped incoming packets per second.
        - name: errors
          type: double
          description: >
            Errors on incoming packets per second.
        - name: packets
          type: double
          description: >
            Incoming packets per second.
    - name: out
      type: group
      description: >
        Outgoing network stats per second.
      fields:
        - name: bytes
          type: double
          format: bytes
          description: >
            Outgoing bytes per second.
        - name: dropped
          type: double
          description: >
            Dropped outgoing packets per second.
        - name: errors
          type: double
          description: >
            Errors on outgoing packets per second.
        - name: packets
          type: double
          description: >
            Outgoing packets per second.
    - name: inbound
      type: group
      description: >
        Incoming network stats since the container started.
      fields:
        - name: bytes
          type: long
          format: bytes
          description: >
            Total number of incoming bytes.
        - name: dropped
          type: long
          description: >
            Total number of dropped incoming packets.
        - name: errors
          type: long
          description: >
            Total errors on incoming packets.
        - name: packets
          type: long
          description: >
            Total number of incoming packets.
    - name: outbound
      type: group
      description: >
        Outgoing network stats since the container started.
      fields:
        - name: bytes
          type: long
          format: bytes
          description: >
            Total number of outgoing bytes.
        - name: dropped
          type: long
          description: >
            Total number of dropped outgoing packets.
        - name: errors
          type: long
          description: >
            Total errors on outgoing packets.
        - name: packets
          type: long
          description: >
            Total number of outgoing packets.
