---
name: Bump golang-version to latest version
pipelineid: 'bump-golang-version'

scms:
  githubConfig:
    kind: github
    spec:
      owner: '{{ .scm.owner }}'
      repository: '{{ .scm.repository }}'
      user: '{{ requiredEnv "GITHUB_ACTOR" }}'
      username: '{{ requiredEnv "GITHUB_ACTOR" }}'
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      branch: '{{ .scm.branch }}'
      commitusingapi: true
      force: false

actions:
  beats:
    kind: github/pullrequest
    scmid: githubConfig
    sourceid: latestGoVersion
    title: '[Automation] Bump Golang version to {{ source "latestGoVersion" }}'
    spec:
      labels:
        - dependencies
        - backport-active-all

sources:
  minor:
    name: Get minor version in .go-version
    kind: shell
    transformers:
      - findsubmatch:
          pattern: '^\d+.(\d+).\d+$'
          captureindex: 1
    spec:
      command: cat .go-version

  latestGoVersion:
    name: Get Latest Go Release
    kind: githubrelease
    dependson:
      - minor
    transformers:
      - trimprefix: v
    spec:
      owner: elastic
      repository: golang-crossbuild
      token: '{{ requiredEnv "GITHUB_TOKEN" }}'
      username: '{{ requiredEnv "GITHUB_ACTOR" }}'
      versionfilter:
        kind: regex
        pattern: v1\.{{ source "minor" }}\.(\d*)$

  gomod:
    dependson:
      - latestGoVersion
    name: Get version in go.mod format
    kind: shell
    transformers:
      - findsubmatch:
          pattern: '^(\d+.\d+).\d+'
          captureindex: 1
    spec:
      command: echo {{ source "latestGoVersion" }}

  golangImageVersion:
    dependson:
      - latestGoVersion
    name: Get the golang image version for Dockerfiles
    kind: shell
    spec:
      command: echo {{ source "latestGoVersion" }}-bookworm

conditions:
  dockerTag:
    name: Is docker image golang:{{ source "golangImageVersion" }} published
    kind: dockerimage
    spec:
      image: golang
      tag: '{{ source "golangImageVersion" }}'
    sourceid: golangImageVersion

  goDefaultVersion-check:
    name: Check if defined golang version differs
    kind: shell
    sourceid: latestGoVersion
    spec:
      command: 'grep -v -q {{ source "latestGoVersion" }} .go-version #'

targets:
  update-gomod:
    name: "Update go.mod"
    sourceid: gomod
    scmid: githubConfig
    kind: file
    spec:
      content: 'go {{ source "latestGoVersion" }}'
      file: go.mod
      matchpattern: 'go \d+.\d+.\d+'
  update-go-version:
    name: "Update .go-version"
    sourceid: latestGoVersion
    scmid: githubConfig
    kind: file
    spec:
      content: '{{ source "latestGoVersion" }}'
      file: .go-version
      matchpattern: '\d+.\d+.\d+'
  update-version.asciidoc:
    name: "Update version.asciidoc"
    sourceid: latestGoVersion
    scmid: githubConfig
    kind: file
    spec:
      content: ':go-version: {{ source "latestGoVersion" }}'
      file: libbeat/docs/version.asciidoc
      matchpattern: ':go-version: \d+.\d+.\d+'
  update-devcontainer:
    name: "Update .devcontainer/devcontainer.json"
    sourceid: gomod
    scmid: githubConfig
    kind: file
    spec:
      content: 'go:1-{{ source "gomod" }}'
      file: ./.devcontainer/devcontainer.json
      matchpattern: 'go:1-\d+.\d+'
  update-auditbeat-dockerfile:
    name: "Update Auditbeat Dockerfile"
    sourceid: golangImageVersion
    scmid: githubConfig
    kind: dockerfile
    spec:
      instruction:
        keyword: "FROM"
        matcher: "golang"
      file: ./auditbeat/Dockerfile
  update-heartbeat-dockerfile:
    name: "Update Heartbeat Dockerfile"
    sourceid: golangImageVersion
    scmid: githubConfig
    kind: dockerfile
    spec:
      instruction:
        keyword: "FROM"
        matcher: "golang"
      file: ./heartbeat/Dockerfile
  update-metricbeat-dockerfile:
    name: "Update Metricbeat Dockerfile"
    sourceid: golangImageVersion
    scmid: githubConfig
    kind: dockerfile
    spec:
      instruction:
        keyword: "FROM"
        matcher: "golang"
      file: ./metricbeat/Dockerfile
  update-packetbeat-dockerfile:
    name: "Update Packetbeat Dockerfile"
    sourceid: golangImageVersion
    scmid: githubConfig
    kind: dockerfile
    spec:
      instruction:
        keyword: "FROM"
        matcher: "golang"
      file: ./packetbeat/Dockerfile
  update-http-module-dockerfile:
    name: "Update HTTP module Dockerfile"
    sourceid: golangImageVersion
    scmid: githubConfig
    kind: dockerfile
    spec:
      instruction:
        keyword: "FROM"
        matcher: "golang"
      file: ./metricbeat/module/http/_meta/Dockerfile
  update-vsphere-module-dockerfile:
    name: "Update from vsphere Dockerfile"
    sourceid: golangImageVersion
    scmid: githubConfig
    kind: dockerfile
    spec:
      instruction:
        keyword: "FROM"
        matcher: "golang"
      file: ./metricbeat/module/vsphere/_meta/Dockerfile
  update-metricbeat-debug-dockerfile:
    name: "Update Metricbeat debug Dockerfile"
    sourceid: golangImageVersion
    scmid: githubConfig
    kind: dockerfile
    spec:
      instruction:
        keyword: "FROM"
        matcher: "golang"
      file: ./dev-tools/kubernetes/metricbeat/Dockerfile.debug
  update-dockerfiles-filebeat-debug:
    name: "Update Filebeat debug Dockerfile"
    sourceid: golangImageVersion
    scmid: githubConfig
    kind: dockerfile
    spec:
      instruction:
        keyword: "FROM"
        matcher: "golang"
      file: ./dev-tools/kubernetes/filebeat/Dockerfile.debug
  update-heartbeat-debug-dockerfile:
    name: "Update Heartbeat debug Dockerfile"
    sourceid: golangImageVersion
    scmid: githubConfig
    kind: dockerfile
    spec:
      instruction:
        keyword: "FROM"
        matcher: "golang"
      file: ./dev-tools/kubernetes/heartbeat/Dockerfile.debug
  update-stan-module-dockerfile:
    name: "Update stan Dockerfile"
    sourceid: golangImageVersion
    scmid: githubConfig
    kind: dockerfile
    spec:
      instruction:
        keyword: "FROM"
        matcher: "golang"
      file: ./x-pack/metricbeat/module/stan/_meta/Dockerfile
