- module: checkpoint
  firewall:
    enabled: false

    # Set which input to use between syslog (default) or file.
    #var.input: syslog

    # The interface to listen to UDP based syslog traffic. Defaults to
    # localhost. Set to 0.0.0.0 to bind to all available interfaces.
    #var.syslog_host: localhost

    # The UDP port to listen for syslog traffic. Defaults to 9001.
    #var.syslog_port: 9001

    # Set internal security zones. used to override parsed network.direction
    # based on zone egress and ingress
    #var.internal_zones: [ "Internal" ]

    # Set external security zones. used to override parsed network.direction
    # based on zone egress and ingress
    #var.external_zones: [ "External" ]
