---
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    labels:
      - automation
      - dependabot
    allow:
      # Team:Elastic-Agent-Data-Plane
      - dependency-name: github.com/elastic/elastic-agent-autodiscover
      - dependency-name: github.com/elastic/elastic-agent-client/*
      - dependency-name: github.com/elastic/elastic-agent-libs
      - dependency-name: github.com/elastic/elastic-agent-shipper-client
      - dependency-name: github.com/elastic/elastic-agent-system-metrics
      - dependency-name: github.com/elastic/go-concert
      - dependency-name: github.com/elastic/go-elasticsearch/*
      - dependency-name: github.com/elastic/go-licenser
      - dependency-name: github.com/elastic/go-lookslike
      - dependency-name: github.com/elastic/go-lumber
      - dependency-name: github.com/elastic/go-structform
      - dependency-name: github.com/elastic/go-sysinfo
      - dependency-name: github.com/elastic/go-ucfg
      - dependency-name: github.com/elastic/gosigar
      - dependency-name: go.elastic.co/apm/*
      - dependency-name: go.elastic.co/ecszap
      - dependency-name: go.elastic.co/go-licence-detector
      # Team:Security-Linux Platform
      - dependency-name: github.com/elastic/go-libaudit/*
      - dependency-name: github.com/elastic/go-perf
      - dependency-name: github.com/elastic/go-seccomp-bpf
      - dependency-name: github.com/elastic/toutoumomoma
      - dependency-name: github.com/elastic/ebpfevents
      # Team:Team:obs-ds-hosted-services, Team:obs-infraobs-integrations
      # AWS SDK dependencies
      - dependency-name: github.com/aws/aws-sdk-go-v2/*
      - dependency-name: github.com/aws/aws-lambda-go/*
      - dependency-name: github.com/aws/smithy-go/*
      # Azure SDK dependencies
      - dependency-name: github.com/Azure/azure-sdk-for-go/*
      - dependency-name: github.com/Azure/azure-event-hubs-go/*
      - dependency-name: github.com/Azure/azure-storage-blob-go/*
      - dependency-name: github.com/Azure/go-autorest/*
      # GCP SDK dependencies
      - dependency-name: cloud.google.com/go/*
    groups:
      # Cloud providers' SDK dependencies
      aws-sdks:
        patterns:
          - "github.com/aws/aws-sdk-go-v2/*"
      azure-sdks:
        patterns:
          - "github.com/Azure/azure-*-go"
          - "github.com/Azure/go-autorest/*"
      gcp-sdks:
        patterns:
          - "cloud.google.com/go/*"
    ignore:
      # Skip github.com/elastic/mito because it requires documentation updates.
      - dependency-name: github.com/elastic/mito
    open-pull-requests-limit: 2

  - package-ecosystem: gomod
    directory: /
    # Workaround to satisfy Dependabot's unique constraint (needs unique 'package-ecosystem', 'directory', 'target-branch' tuples)
    # for duplicate package-ecosystem configurations: https://github.com/dependabot/dependabot-core/issues/1778#issuecomment-1988140219
    target-branch: main
    schedule:
      interval: daily
    cooldown:
      semver-major-days: 30
      semver-minor-days: 3
      semver-patch-days: 1
    labels:
      - automation
      - dependabot
      - Team:Obs-InfraObs
    allow:
      # Protocol dependencies
      - dependency-name: github.com/elastic/bayeux
      # Database driver dependencies
      - dependency-name: github.com/go-sql-driver/mysql
      - dependency-name: github.com/lib/pq
      - dependency-name: github.com/godror/godror
      - dependency-name: github.com/microsoft/go-mssqldb
      # Windows dependencies
      - dependency-name: "github.com/microsoft/wmi"
      - dependency-name: "github.com/go-ole/go-ole"
      - dependency-name: "github.com/StackExchange/wmi"

      # meraki
      - dependency-name: "github.com/go-resty/resty/v2"
      - dependency-name: "github.com/tomnomnom/linkheader"
      - dependency-name: "github.com/meraki/dashboard-api-go/v3"
      # haproxy
      - dependency-name: "github.com/gocarina/gocsv"
      # salesforce
      - dependency-name: "github.com/elastic/go-sfdc"
      # vsphere
      - dependency-name: "github.com/vmware/govmomi"
      # redis
      - dependency-name: "github.com/gomodule/redigo"
      # panw
      - dependency-name: "github.com/PaloAltoNetworks/pango"
      # mongodb
      - dependency-name: "go.mongodb.org/mongo-driver"
    groups:
      windows:
        patterns:
          - "github.com/microsoft/wmi"
          - "github.com/go-ole/go-ole"
          - "github.com/StackExchange/wmi"
    open-pull-requests-limit: 5

  # Update integration test container images
  - package-ecosystem: "docker"
    directories:
      # Starting with the sredis image, we might want to add other images later.
      - '/testing/environments/docker/sredis'
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "23:29"
    labels:
      - automation
      - dependabot

  # GitHub actions
  - package-ecosystem: "github-actions"
    directories:
      - '/'
      - '/.github/actions/*'
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "22:00"
    labels:
      - automation
      - dependabot
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
