- name: volume
  type: group
  description: >
    kubernetes volume metrics
  release: ga
  fields:
    - name: name
      type: keyword
      description: >
        Volume name
    - name: fs
      type: group
      fields:
        - name: capacity
          type: group
          fields:
            - name: bytes
              type: double
              format: bytes
              description: >
                Filesystem total capacity in bytes
        - name: available
          type: group
          fields:
            - name: bytes
              type: double
              format: bytes
              description: >
                Filesystem total available in bytes
        - name: used
          type: group
          fields:
            - name: bytes
              type: double
              format: bytes
              description: >
                Filesystem total used in bytes
            - name: pct
              type: scaled_float
              format: percent
              description: >
                Percentage of used storage
        - name: inodes
          type: group
          fields:
            - name: used
              type: double
              description: >
                Used inodes
            - name: free
              type: double
              description: >
                Free inodes
            - name: count
              type: double
              description: >
                Total inodes
            - name: pct
              type: scaled_float
              format: percent
              description: >
                Percentage of used inodes

