version: '2.3'

services:
  aerospike:
    image: docker.elastic.co/integrations-ci/beats-aerospike:${AEROSPIKE_VERSION:-7.2.0.1}-1
    ulimits:
      nofile:
        soft: 20000
        hard: 20000
    build:
      context: ./_meta
      args:
        AEROSPIKE_VERSION: ${AEROSPIKE_VERSION:-7.2.0}
    ports:
      - 3000
