type: log
paths:
{{ range $i, $path := .paths }}
 - {{$path}}
{{ end }}
exclude_files: [".gz$","_slowlog.log$","_access.log$","_deprecation.log$"]
multiline:
  pattern: '^(\[[0-9]{4}-[0-9]{2}-[0-9]{2}|{)'
  negate: true
  match: after

processors:
# Locale for timezone is only needed in non-json logs
- add_locale.when.not.regexp.message: "^{" 
