- name: persistentvolume
  type: group
  description: >
    kubernetes persistent volume metrics from kube-state-metrics
  release: experimental
  fields:
    - name: name
      type: keyword
      description: Volume name.
    - name: capacity.bytes
      type: long
      description: Volume capacity
    - name: phase
      type: keyword
      description: Volume phase according to kubernetes
    - name: storage_class
      type: keyword
      description: Storage class for the volume
      
      

