version: '3.7'

services:
  appsearch:
    build:
      context: ./_meta
    depends_on:
      - elasticsearch
    environment:
      - "elasticsearch.host=http://elasticsearch:9200"
      - "allow_es_settings_modification=true"
      - "JAVA_OPTS=-Xms2g -Xmx2g"
    ports:
      - 3002
    command: --process app-server

  elasticsearch:
    extends:
      file: ../../../metricbeat/docker-compose.yml
      service: elasticsearch
    environment:
      - "bootstrap.memory_lock=true"
      - "action.auto_create_index=.app-search-*-logs-*,-.app-search-*,+*"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
