version: '2.3'

services:
  etcd:
    image: docker.elastic.co/integrations-ci/beats-etcd:${ETCD_VERSION:-3.3.10}-1
    build:
      context: ${ETCD_PATH:-.}/_meta
      args:
        ETCD_VERSION: ${ETCD_VERSION:-3.3.10}
    ports:
      - 2379
