- module: salesforce

  apex:
    enabled: false
    var.api_version: 56

    var.jwt_enabled: true

    var.client_id: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    var.client_username: "abc.xyz@mail.com"
    var.client_key_path: client_key.pem
    var.jwt_url: https://login.salesforce.com

    var.client_secret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    var.token_url: "https://login.salesforce.com"
    var.user: "abc.xyz@mail.com"
    var.password: "P@$$W0道"

    var.url: "https://instance_id.my.salesforce.com"
    var.elf_interval: 1h
      
  login:
    enabled: false
    var.api_version: 56

    var.jwt_enabled: true

    var.client_id: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    var.client_username: "abc.xyz@mail.com"
    var.client_key_path: client_key.pem
    var.jwt_url: https://login.salesforce.com

    var.client_secret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    var.token_url: "https://login.salesforce.com"
    var.user: "abc.xyz@mail.com"
    var.password: "P@$$W0道"

    var.url: "https://instance_id.my.salesforce.com"

    var.event_log_file: true
    var.elf_interval: 1h
    var.real_time: true
    var.real_time_interval: 5m

  logout:
    enabled: false
    var.api_version: 56

    var.jwt_enabled: true

    var.client_id: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    var.client_username: "abc.xyz@mail.com"
    var.client_key_path: client_key.pem
    var.jwt_url: https://login.salesforce.com

    var.client_secret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    var.token_url: "https://login.salesforce.com"
    var.user: "abc.xyz@mail.com"
    var.password: "P@$$W0道"

    var.url: "https://instance_id.my.salesforce.com"

    var.event_log_file: true
    var.elf_interval: 1h
    var.real_time: true
    var.real_time_interval: 5m

  setupaudittrail:
    enabled: false
    var.api_version: 56

    var.jwt_enabled: true

    var.client_id: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    var.client_username: "abc.xyz@mail.com"
    var.client_key_path: client_key.pem
    var.jwt_url: https://login.salesforce.com

    var.client_secret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    var.token_url: "https://login.salesforce.com"
    var.user: "abc.xyz@mail.com"
    var.password: "P@$$W0道"

    var.url: "https://instance_id.my.salesforce.com"

    var.real_time: true
    var.real_time_interval: 5m
