type: log
paths:
{{ range $i, $path := .paths }}
 - {{$path}}
{{ end }}
exclude_files: [".gz$"]
tags: {{.tags}}

json.keys_under_root: false

processors:
  - drop_fields:
      fields: ["json.orig_bytes","json.resp_bytes","json.tunnel_parents"]
  - rename:
      fields:
        - from: "json"
          to: "zeek.connection"

        - from: "zeek.connection.duration"
          to: "temp.duration"

        - from: "zeek.connection.id.orig_h"
          to: "source.address"

        - from: "zeek.connection.id.orig_p"
          to: "source.port"

        - from: "zeek.connection.id.resp_h"
          to: "destination.address"

        - from: "zeek.connection.id.resp_p"
          to: "destination.port"

        - from: "zeek.connection.proto"
          to: "network.transport"

        - from: "zeek.connection.service"
          to: "network.protocol"

        - from: "zeek.connection.uid"
          to: "zeek.session_id"

        - from: "zeek.connection.orig_ip_bytes"
          to: "source.bytes"

        - from: "zeek.connection.resp_ip_bytes"
          to: "destination.bytes"

        - from: "zeek.connection.orig_pkts"
          to: "source.packets"

        - from: "zeek.connection.resp_pkts"
          to: "destination.packets"

        - from: "zeek.connection.conn_state"
          to: "zeek.connection.state.code"

        - from: "zeek.connection.orig_l2_addr"
          to: "source.mac"

        - from: "zeek.connection.resp_l2_addr"
          to: "destination.mac"

      ignore_missing: true
      fail_on_error: false

  - rename:
      when.equals.network.transport: icmp
      fields:
        - from: "source.port"
          to: "zeek.connection.icmp.type"

        - from: "destination.port"
          to: "zeek.connection.icmp.code"

      ignore_missing: true
      fail_on_error: false

{{ if .community_id }}
  - if:
      equals.network.transport: icmp
    then:
      community_id:
        fields:
          source_ip: source.address
          destination_ip: destination.address
          icmp_type: zeek.connection.icmp.type
          icmp_code: zeek.connection.icmp.code
    else:
      community_id:
        fields:
          source_ip: source.address
          destination_ip: destination.address
{{ end }}
