- name: scheduler
  type: group
  description: >
    Kubernetes scheduler metrics
  release: ga
  fields:
  - name: handler
    type: keyword
    description: >
      Request handler
  - name: code
    type: keyword
    description: >
      HTTP code
  - name: method
    type: keyword
    description: >
      HTTP method
  - name: host
    type: keyword
    description: >
      Request host
  - name: name
    type: keyword
    description: >
      Name for the resource
  - name: result
    type: keyword
    description: >
      Schedule attempt result
  - name: operation
    type: keyword
    description: >
      Scheduling operation
  - name: process
    type: group
    fields:
      - name: cpu.sec
        type: double
        description: CPU seconds
      - name: memory.resident.bytes
        type: long
        format: bytes
        description: Bytes in resident memory
      - name: memory.virtual.bytes
        type: long
        format: bytes
        description: Bytes in virtual memory
      - name: fds.open.count
        type: long
        description: Number of open file descriptors
      - name: started.sec
        type: double
        description: Seconds since the process started
  - name: http
    type: group
    fields:
      - name: request.duration.us.percentile.*
        type: object
        object_type: double
        description: Request duration microseconds percentiles
      - name: request.duration.us.sum
        type: double
        description: Request duration microseconds cumulative sum
      - name: request.duration.us.count
        type: long
        description: Request count for duration
      - name: request.size.bytes.percentile.*
        type: object
        object_type: long
        description: Request size percentiles
      - name: request.size.bytes.sum
        type: long
        format: bytes
        description: Request size cumulative sum
      - name: request.size.bytes.count
        type: long
        description: Request count for size
      - name: response.size.bytes.percentile.*
        type: object
        object_type: long
        description: Response size percentiles
      - name: response.size.bytes.sum
        type: long
        format: bytes
        description: Response size cumulative sum
      - name: response.size.bytes.count
        type: long
        description: Response count
      - name: request.count
        type: long
        description: Request count
  - name: client.request.count
    type: long
    description: >
      Number of requests as client
  - name: leader.is_master
    type: boolean
    description: >
      Whether the node is master

  - name: scheduling
    type: group
    fields:
      - name: e2e.duration.us.bucket.*
        type: object
        object_type: long
        description: End to end scheduling duration microseconds
      - name: e2e.duration.us.sum
        type: long
        description: End to end scheduling duration microseconds sum
      - name: e2e.duration.us.count
        type: long
        description: End to end scheduling count
      - name: pod.preemption.victims.count
        type: long
        description: Pod preemption victims
      - name: pod.attempts.count
        type: long
        description: Pod attempts count
      - name: duration.seconds.percentile.*
        type: object
        object_type: double
        description: Scheduling duration percentiles
      - name: duration.seconds.sum
        type: double
        description: Scheduling duration cumulative sum
      - name: duration.seconds.count
        type: long
        description: Scheduling count

