- module: containerd
  metricsets: ["cpu", "memory", "blkio"]
  period: 10s
  # containerd metrics endpoint is configured in /etc/containerd/config.toml
  # Metrics endpoint does not listen by default
  # https://github.com/containerd/containerd/blob/main/docs/man/containerd-config.toml.5.md
  hosts: ["localhost:1338"]
  # if set to true, cpu and memory usage percentages will be calculated. Default is true
  calcpct.cpu: true
  calcpct.memory: true

