{{ if eq .input "httpjson" }}

type: httpjson
config_version: "2"
interval: {{ .interval }}

auth.basic.user: {{ .username }}
auth.basic.password: {{ .password }}

request.method: GET
request.ssl: {{ .ssl | tojson }}
request.url: {{ .url }}
request.redirect.forward_headers: true
request.transforms:
- set:
    target: header.Content-Type
    value: application/vnd.oasis.taxii+json
- set:
    target: header.Accept
    value: application/vnd.oasis.taxii+json
- set:
    target: header.Range
    value: items 0-10000
- set:
    target: url.params.match[type]
    value: {{ .types }}
- set:
    target: url.params.added_after
    value: '[[.cursor.timestamp]]'
    default: '[[ formatDate (now (parseDuration "-{{ .first_interval }}")) "2006-01-02T15:04:05.999Z" ]]'

response.split:
  target: body.results

cursor:
  timestamp:
    value: '[[ .last_response.header.Get "X-TAXII-Date-Added-Last" ]]'

{{ else if eq .input "file" }}

type: log
paths:
{{ range $i, $path := .paths }}
  - {{$path}}
{{ end }}
exclude_files: [".gz$"]

{{ end }}

tags: {{.tags | tojson}}
publisher_pipeline.disable_host: {{ inList .tags "forwarded" }}

processors:
  - decode_json_fields:
      fields: [message]
      document_id: id
      target: json
  - add_fields:
      target: ''
      fields:
        ecs.version: 1.6.0
