version: '2.3'

services:
  traefik:
    image: docker.elastic.co/integrations-ci/beats-traefik:${TRAEFIK_VERSION:-1.6}-1
    build:
      context: ${TRAEFIK_PATH:-.}/_meta
      args:
        TRAEFIK_VERSION: ${TRAEFIK_VERSION:-1.6}
    ports:
     - 8080
