- module: googlecloud
  metricsets:
    - compute
    - pubsub
  zone: "us-central1-a"
  project_id: "your project id"
  credentials_file_path: "your JSON credentials file path"
  exclude_labels: false
  period: 300s
