#- module: nginx
  # Access logs
  #access:
    #enabled: true

    # Ingest Node pipeline to use. Options are `with_plugins` (default)
    # and `no_plugins`. Use `no_plugins` if you don't have the geoip or
    # the user agent Node ingest plugins installed.
    #var.pipeline: with_plugins

    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    #var.paths:

    # Prospector configuration (advanced). Any prospector configuration option
    # can be added under this section.
    #prospector:

  # Error logs
  #error:
    #enabled: true

    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    #var.paths:

    # Prospector configuration (advanced). Any prospector configuration option
    # can be added under this section.
    #prospector:
