- name: info
  type: group
  description: >
    Info metrics based on https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/display-system-wide-information.
  release: ga
  fields:
    - name: containers
      type: group
      description: >
        Overall container stats.
      fields:
        - name: paused
          type: long
          description: >
            Total number of paused containers.
        - name: running
          type: long
          description: >
            Total number of running containers.
        - name: stopped
          type: long
          description: >
            Total number of stopped containers.
        - name: total
          type: long
          description: >
            Total number of existing containers.
    - name: id
      type: keyword
      description: >
        Unique Docker host identifier.

    - name: images
      type: long
      description: >
        Total number of existing images.
