- name: memory
  type: group
  description: >
    Memory metrics.
  release: ga
  fields:
    - name: stats.*
      type: object
      object_type: long
      object_type_mapping_type: "*"
      description: >
        Raw memory stats from the cgroups memory.stat interface
    - name: commit
      type: group
      description: >
        Committed bytes on Windows
      fields:
        - name: total
          type: long
          format: bytes
          description: >
            Total bytes
        - name: peak
          type: long
          format: bytes
          description: >
            Peak committed bytes on Windows
    - name: private_working_set.total
      type: long
      format: bytes
      description: >
        private working sets on Windows
    - name: fail.count
      type: scaled_float
      description: >
        Fail counter.
    - name: limit
      type: long
      format: bytes
      description: >
        Memory limit.
    - name: rss
      type: group
      description: >
        RSS memory stats.
      fields:
        - name: total
          type: long
          format: bytes
          description: >
            Total memory resident set size.
        - name: pct
          type: scaled_float
          format: percent
          description: >
            Memory resident set size percentage.
    - name: usage
      type: group
      description: >
        Usage memory stats.
      fields:
        - name: max
          type: long
          format: bytes
          description: >
            Max memory usage.
        - name: pct
          type: scaled_float
          format: percent
          description: >
            Memory usage percentage.
        - name: total
          type: long
          format: bytes
          description: >
            Total memory usage.

