- module: oracle
  period: 10m
  metricsets:
    - tablespace
  enabled: true
  hosts: ["user/pass@0.0.0.0:1521/ORCLPDB1.localdomain"]
- module: oracle
  period: 10s
  metricsets:
    - performance
  enabled: true
  hosts: ["user/pass@0.0.0.0:1521/ORCLPDB1.localdomain"]
- module: oracle
  period: 10m
  metricsets:
    - sysmetric
  enabled: true
  # patterns: ["foo%","%bar","%foobar%"]
  hosts: ["user/pass@0.0.0.0:1521/ORCLPDB1.localdomain"]
  
  # username: ""
  # password: ""

