- module: pensando
# Firewall logs
  dfw:
    enabled: false
    var.syslog_host: 0.0.0.0
    var.syslog_port: 9001

    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    # var.paths:
