dist:
  name: otelcol-beats
  otelcol_version: 0.145.0
  output_path: ./build/otelcol-beats
  cgo_enabled: true

receivers:
  - gomod: github.com/elastic/beats/v7 v7.0.0
    import: github.com/elastic/beats/v7/x-pack/filebeat/fbreceiver
  - gomod: github.com/elastic/beats/v7 v7.0.0
    import: github.com/elastic/beats/v7/x-pack/metricbeat/mbreceiver

processors:
  - gomod: github.com/elastic/beats/v7 v7.0.0
    import: github.com/elastic/beats/v7/x-pack/otel/processor/beatprocessor

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.145.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter v0.145.0
  - gomod: github.com/elastic/beats/v7 v7.0.0
    import: github.com/elastic/beats/v7/x-pack/otel/exporter/logstashexporter

extensions:
  - gomod: github.com/elastic/beats/v7 v7.0.0
    import: github.com/elastic/beats/v7/x-pack/otel/extension/beatsauthextension

replaces:
  - github.com/elastic/beats/v7 => ../../../..
  - github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/consumption/armconsumption => github.com/elastic/azure-sdk-for-go/sdk/resourcemanager/consumption/armconsumption v1.1.0-elastic
  - github.com/apoydence/eachers => github.com/poy/eachers v0.0.0-20181020210610-23942921fe77
  - github.com/dop251/goja => github.com/elastic/goja v0.0.0-20190128172624-dd2ac4456e20
  - github.com/fsnotify/fsevents => github.com/elastic/fsevents v0.0.0-20181029231046-e1d381a4d270
  - github.com/fsnotify/fsnotify => github.com/elastic/fsnotify v1.6.1-0.20240920222514-49f82bdbc9e3
  - github.com/google/gopacket => github.com/elastic/gopacket v1.1.20-0.20241002174017-e8c5fda595e6
  - github.com/meraki/dashboard-api-go/v3 => github.com/tommyers-elastic/dashboard-api-go/v3 v3.0.0-20250616163611-a325b49669a4
