type: s3
queue_url: {{ .queue_url }}

{{ if .credential_profile_name }}
credential_profile_name: {{ .credential_profile_name }}
{{ end }}

{{ if .shared_credential_file }}
shared_credential_file: {{ .shared_credential_file }}
{{ end }}

{{ if .visibility_timeout }}
visibility_timeout: {{ .visibility_timeout }}
{{ end }}

{{ if .api_timeout }}
api_timeout: {{ .api_timeout }}
{{ end }}

{{ if .endpoint }}
endpoint: {{ .endpoint }}
{{ end }}

{{ if .access_key_id }}
access_key_id: {{ .access_key_id }}
{{ end }}

{{ if .secret_access_key }}
secret_access_key: {{ .secret_access_key }}
{{ end }}

{{ if .session_token }}
session_token: {{ .session_token }}
{{ end }}
