type: log
paths:
{{ range $i, $path := .paths }}
 - {{$path}}
{{ end }}
exclude_files: [".gz$"]
tags: {{.tags}}

json.keys_under_root: false

fields_under_root: true
fields:
  network.transport: tcp

processors:
  - rename:
      fields:
        - from: "json"
          to: "zeek.dce_rpc"

        - from: "zeek.dce_rpc.id.orig_h"
          to: "source.ip"

        - from: "zeek.dce_rpc.id.orig_p"
          to: "source.port"

        - from: "zeek.dce_rpc.id.resp_h"
          to: "destination.ip"

        - from: "zeek.dce_rpc.id.resp_p"
          to: "destination.port"

        - from: "zeek.dce_rpc.uid"
          to: "zeek.session_id"

      ignore_missing: true
      fail_on_error: false

{{ if .community_id }}
  - community_id:
{{ end }}
