version: '3.7'

services:
  consul:
    image: docker.elastic.co/integrations-ci/beats-consul:${CONSUL_VERSION:-1.4.2}-1
    build:
      context: ./_meta
      args:
        CONSUL_VERSION: ${CONSUL_VERSION:-1.4.2}
    ports:
      - 8500
