when:
    branches: true             ## for all the branches
    changeset:                 ## when PR contains any of those entries in the changeset
        - "^deploy/kubernetes/.*"
        - "^libbeat/docs/version.asciidoc"
    comments:                  ## when PR comment contains any of those entries
        - "/test deploy/kubernetes"
    labels:                    ## when PR labels matches any of those entries
        - "kubernetes"
    parameters:                ## when parameter was selected in the UI.
        - "kubernetes"
    tags: true                 ## for all the tags
platform: "immutable && ubuntu-22" ## default label for all the stages
stages:
    k8sTest:
        k8sTest: "v1.29.0,v1.28.0,v1.27.3,v1.26.6"
        stage: mandatory
