- module: awsfargate
  log:
    enabled: false

    # Filename of AWS credential file
    # If not set "$HOME/.aws/credentials" is used on Linux/Mac
    # "%UserProfile%\.aws\credentials" is used on Windows
    #var.shared_credential_file: /etc/filebeat/aws_credentials

    # Profile name for aws credential
    # If not set the default profile is used
    #var.credential_profile_name: fb-aws

    # Use access_key_id, secret_access_key and/or session_token instead of shared credential file
    #var.access_key_id: access_key_id
    #var.secret_access_key: secret_access_key
    #var.session_token: session_token

    # Maximum duration before AWS API request will be interrupted
    # Default to be 120s
    #var.api_timeout: 120s

    # Custom endpoint used to access AWS APIs
    #var.endpoint: amazonaws.com

    # AWS IAM Role to assume
    #var.role_arn: arn:aws:iam::123456789012:role/test-mb

    # ARN of the log group to collect logs from
    #var.log_group_arn: arn:aws:logs:us-east-1:123456789012:log-group:test:*

    # Name of the log group to collect logs from
    #var.log_group_name: /ecs/test-log-group

    # Region that the specified log group belongs to
    #var.region_name: us-east-1

    # A list of strings of log streams names that Filebeat collect log events from
    #var.log_streams: ["/ecs/test-log-group/test-log-stream"]

    # A string to filter the results to include only log events from log streams that have names starting with this prefix
    #var.log_stream_prefix: /ecs/test-log-group/

    # Specify if Filebeat should read log files from the beginning or from the end
    # Default start_position is beginning
    #var.start_position: beginning

    # How often Filebeat checks for new log events from the specified log group
    # Default scan_frequency is 1 minute
    #var.scan_frequency: 1m

    # Time used to sleep between AWS FilterLogEvents API calls inside the same collection period
    # Default api_sleep is 200 ms
    #var.api_sleep: 200ms

    # URL to proxy AWS API calls
    #var.proxy_url: http://proxy:3128

    # Configures the SSL settings, ie. set trusted CAs, ignore certificate verification....
    #var.ssl:
