- module: okta
  system:
    enabled: false
    # You must configure the URL with your Okta domain and provide an
    # API token to access the logs API.
    #var.url: https://yourOktaDomain/api/v1/logs
    #var.api_key: 'yourApiTokenHere'
