version: '2.3'

services:
  ibmmq:
    image: docker.elastic.co/observability-ci/beats-integration-ibmmq:${IBMMQ_VERSION:-9.1.4.0-r1-amd64}-1
    build:
      context: ./_meta
      args:
        IBMMQ_VERSION: ${IBMMQ_VERSION:-9.1.4.0-r1-amd64}
    ports:
      - 9157
