name: auditbeat-macos-unit-tests

env:
  BEAT: "auditbeat"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - auditbeat/**
      # OSS
      - go.mod
      - dev-tools/**
      - libbeat/**
      # Workflow
      - .github/workflows/auditbeat-macos-unit-tests.yml
      - .github/actions/unit-test/action.yml
  push:
    branches:
      - main
    paths:
      - auditbeat/**
      # OSS
      - go.mod
      - dev-tools/**
      - libbeat/**
      # Workflow
      - .github/workflows/auditbeat-macos-unit-tests.yml
      - .github/actions/unit-test/action.yml

permissions:
  contents: read

## Concurrency only allowed in the main branch.
## So old builds running for old commits within the same Pull Request are cancelled
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  unit-tests-branch:
    name: Unit tests ${{ matrix.os }}
    if: github.event_name == 'push'
    strategy:
      fail-fast: false
      matrix:
        # Disabled due to: https://github.com/elastic/beats/issues/43482
        # TODO uncomment for testing or once solved
        os: [macos-13] #, macos-14]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/unit-test
        with:
          beat: ${{ env.BEAT }}

  unit-tests-pr:
    name: Unit tests macos-15
    # Disabled due to: https://github.com/elastic/beats/issues/43482
    # TODO: remove the `if: false` and uncomment `if: github.event_name == 'pull_request'`for testing or once solved
    if: false
#    if: github.event_name == 'pull_request'
    runs-on: [macos-15]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/unit-test
        with:
          beat: ${{ env.BEAT }}
