name: check-x-pack-winlogbeat

on:
  pull_request:
    paths:
      - '.github/workflows/check-xpack-winlogbeat.yml'
      - 'x-pack/winlogbeat/**'
      - 'winlogbeat/**'

env:
  BEAT_MODULE: 'x-pack/winlogbeat'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: .go-version
    - name: Run check/update
      uses: magefile/mage-action@v3
      with:
        args: check update
        workdir: "${{ env.BEAT_MODULE }}"
