name: packetbeat

on:
  pull_request:
    paths:
      - '.github/workflows/macos-packetbeat.yml'
  push:
    branches:
      - main
      - 7.1*
      - 8.*

env:
  BEAT_MODULE: 'packetbeat'

permissions:
  contents: read

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v3
      with:
        go-version-file: .go-version
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run:  go install github.com/magefile/mage
    - name: Run build
      run: cd ${{ env.BEAT_MODULE }} && mage build
    - name: Run test
      run: cd ${{ env.BEAT_MODULE }} && mage unitTest
    - uses: v1v/otel-upload-test-artifact-action@v2
      if: always()
      continue-on-error: true
      with:
        jobName: "macos"
        stepName: "Run test"
        path: "${{ env.BEAT_MODULE }}/build/TEST*.xml"
        type: "junit"
        githubToken: ${{ secrets.GITHUB_TOKEN }}
