---
name: notify-stalled-snapshots

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * 7'

permissions:
  contents: read

jobs:
  filter:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      matrix: ${{ steps.generator.outputs.matrix }}
    steps:
      - id: generator
        uses: elastic/apm-pipeline-library/.github/actions/elastic-stack-snapshot-branches@current

  notify:
    runs-on: ubuntu-latest
    needs: [filter]
    strategy:
      matrix: ${{ fromJson(needs.filter.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: "${{ matrix.branch }}"

      - id: search
        run: |-
          if git --no-pager \
            log --pretty=format: \
              --name-only \
              --since="7 days ago" \
            | grep 'testing/environments/snapshot.yml' ; then
            echo "found=false" >> $GITHUB_OUTPUT
          else
            echo "found=true" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ github.token }}

      - if: ${{ contains(steps.search.outputs.found, 'true') }}
        name: Report obsoleted branches
        uses: elastic/apm-pipeline-library/.github/actions/slack-message@current
        with:
          url: ${{ secrets.VAULT_ADDR }}
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          #channel: "#ingest-notifications"
          channel: "#observablt-bots"
          message: "Elastic Stack version for the ${{ matrix.branch }} branch has not been updated for a while ( > 7 days). Review the (<https://github.com/elastic/beats/pulls?q=is%3Apr+is%3Aopen+label%3ATeam%3ABeats-On-Call|open PRs>)"
