name: xpack-auditbeat-macos-unit-tests

env:
  BEAT: "x-pack/auditbeat"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - auditbeat/**
      - x-pack/auditbeat/**
      # OSS
      - go.mod
      - pytest.ini
      - dev-tools/**
      - libbeat/**
      - x-pack/libbeat/**
      # Workflow
      - .github/workflows/xpack-auditbeat-macos-unit-tests.yml
      - .github/actions/unit-test/action.yml
  push:
    branches:
      - main
    paths:
      - auditbeat/**
      - x-pack/auditbeat/**
      # OSS
      - go.mod
      - pytest.ini
      - dev-tools/**
      - libbeat/**
      - x-pack/libbeat/**
      # Workflow
      - .github/workflows/xpack-auditbeat-macos-unit-tests.yml
      - .github/actions/unit-test/action.yml

permissions:
  contents: read

## Concurrency only allowed in the main branch.
## So old builds running for old commits within the same Pull Request are cancelled
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  unit-tests:
    name: Unit tests ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15-intel, macos-15]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/unit-test
        with:
          beat: ${{ env.BEAT }}
