name: xpack-heartbeat-macos-unit-tests

env:
  BEAT: "x-pack/heartbeat"
  NODEJS_VERSION: "22.20.0"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - heartbeat/**
      - x-pack/heartbeat/**
      # OSS
      - go.mod
      - dev-tools/**
      - libbeat/**
      - x-pack/libbeat/**
      # Workflow
      - .github/workflows/xpack-heartbeat-macos-unit-tests.yml
      - .github/actions/unit-test/action.yml
  push:
    branches:
      - main
    paths:
      - heartbeat/**
      - x-pack/heartbeat/**
      # OSS
      - go.mod
      - dev-tools/**
      - libbeat/**
      - x-pack/libbeat/**
      # Workflow
      - .github/workflows/xpack-heartbeat-macos-unit-tests.yml
      - .github/actions/unit-test/action.yml

permissions:
  contents: read

## Concurrency only allowed in the main branch.
## So old builds running for old commits within the same Pull Request are cancelled
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  unit-tests:
    name: Unit tests ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        os: [macos-15-intel, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODEJS_VERSION }}

      - run: npm i -g @elastic/synthetics

      - uses: ./.github/actions/unit-test
        with:
          beat:  ${{ env.BEAT }}
